const blogPosts = [
    {
        id:1,
        image:"/images/road.png",
        date:"12 FEB",
        category:"TRAVEL",
        author:"J.Stoyn",
        title:"List road trips for every decade of your life",
        text:"There’s nothing quite like being out on the open road. It’s freeing to pack up the car and take on the role of the pilot, stopping on a whim or making a detour when something catches your eye",
    },
    {
        id:2,
        image:"images/parasute.png",
        date:"12 FEB",
        category:"LIFESTYLE",
        author:"A.Tomson",
        title:"The best places for extreme jumping",
        text:"People have invented a lot in the search for a source of thrill. We will tell you about which places on the planet are especially good for getting off the ground in this article",
    },
    {
        id:3,
        image:"images/pleces.png",
        date:"12 FEB",
        category:"INSPIRATION",
        author:"J.Stoyn",
        title:"TOP 10 unusual places in the world",
        text:"Looking at these photos, it's difficult to imagine that everything is a creation of nature. We invite you to see this for yourself by planning a trip to one of the places on our list",
    },
    {
        id:4,
        image:"images/photo.png",
        date:"12 FEB",
        category:"PHOTOGRAPHY",
        author:"A.Tomson",
        title:"Amazing photography examples around the world",
        text:"An amazing photography fully expresses your feelings and making people comfortable to pose is a wonderful achievement",
    },
    {
        id:5,
        image:"images/photo.png",
        date:"12 FEB",
        category:"FASHION",
        author:"A.Tomson",
        title:"Amazing photography examples around the world",
        text:"An amazing photography fully expresses your feelings and making people comfortable to pose is a wonderful achievement",
    },
    {
        id:6,
        image:"images/photo.png",
        date:"12 FEB",
        category:"FOOD",
        author:"A.Tomson",
        title:"Amazing photography examples around the world",
        text:"An amazing photography fully expresses your feelings and making people comfortable to pose is a wonderful achievement",
    },
    {
        id:7,
        image:"images/photo.png",
        date:"12 FEB",
        category:"LIFESTYLE",
        author:"A.Tomson",
        title:"Amazing photography examples around the world",
        text:"An amazing photography fully expresses your feelings and making people comfortable to pose is a wonderful achievement",
    },
    {
        id:7,
        image:"images/photo.png",
        date:"12 FEB",
        category:"TRAVEL",
        author:"A.Tomson",
        title:"Amazing photography examples around the world",
        text:"An amazing photography fully expresses your feelings and making people comfortable to pose is a wonderful achievement",
    },
]

export default blogPosts