const blogPosts = [
    {
        id:1,
        image:"/images/road.png",
        date:"12 FEB",
        category:"TRAVEL",
        author:"J.Stoyn",
        title:"List road trips for every decade of your life",
        text:"There’s nothing quite like being out on the open road. It’s freeing to pack up the car and take on the role of the pilot, stopping on a whim or making a detour when something catches your eye",
    },
    {
        id:2,
        image:"images/parasute.png",
        date:"12 FEB",
        category:"LIFESTYLE",
        author:"A.Tomson",
        title:"The best places for extreme jumping",
        text:"People have invented a lot in the search for a source of thrill. We will tell you about which places on the planet are especially good for getting off the ground in this article",
    },
    {
        id:3,
        image:"images/pleces.png",
        date:"12 FEB",
        category:"INSPIRATION",
        author:"J.Stoyn",
        title:"TOP 10 unusual places in the world",
        text:"Looking at these photos, it's difficult to imagine that everything is a creation of nature. We invite you to see this for yourself by planning a trip to one of the places on our list",
    },
    {
        id:4,
        image:"images/photo.png",
        date:"12 FEB",
        category:"PHOTOGRAPHY",
        author:"A.Tomson",
        title:"Amazing photography examples around the world",
        text:"An amazing photography fully expresses your feelings and making people comfortable to pose is a wonderful achievement",
    },
    {
        id:5,
        image:"images/trends.png",
        date:"12 FEB",
        category:"FASHION",
        author:"A.Tomson",
        title:"Spring/Summer 2021 Trends: The Most Important Fashion Looks",
        text:"When viewing the spring summer 2021 collections you need to first acknowledge the context in which these looks were created—designers around the world were all working during lockdown, many away from their studios and usual resources, divided from their teams and facing huge logistical challenges.",
    },
    {
        id:6,
        image:"images/foodtrends.png",
        date:"12 FEB",
        category:"FOOD",
        author:"A.Tomson",
        title:"The Top 21 Main Food Trends of 2021 Year",
        text:"Yearly trends in dining and cooking can be difficult to predict, and the food trends in 2021 are no exception. But after a stressful 2020, many people have turned to food more than ever as a means of comfort, wellbeing and community.",
    },
    {
        id:7,
        image:"images/healthyhabits.png",
        date:"12 FEB",
        category:"LIFESTYLE",
        author:"A.Tomson",
        title:"7 Important Healthy Habits for a Healthy Life",
        text:"It’s a truism that most of us want to live long, happy, successful, and healthy lives. Unfortunately, in our pursuit of success we often take shortcuts with our health—and wind up suffering from various ailments and disabilities that we could have avoided.",
    },
    {
        id:8,
        image:"images/visitindia.png",
        date:"03 FEB",
        category:"TRAVEL",
        author:"A.Tomson",
        title:"20 Best Destinations To Visit In India",
        text:"Many travelers are not aware of the fact that September is a great month to plan a holiday trip in India. It marks the last month of monsoon welcoming an overall pleasant weather.",
    },
    {
        id:9,
        image:"images/ashraful.png",
        date:"03 MAR",
        category:"PHOTOGRAPHY",
        author:"J.Stoyn",
        title:"Delightful photographs of Ashraful Arefin",
        text:"Today we will recharge with positive energy from the delightful photographs of Ashraful Arefin",
    },
    {
        id:10,
        image:"images/success.png",
        date:"03 MAR",
        category:"INSPIRATION",
        author:"A.Tomson",
        title:"13 Things You Should Give Up If You Want To Be Successful",
        text:"Sometimes, to become successful, we do not need to add more things, we need to give up on some of them",
    },
    {
        id:11,
        image:"images/paintсolors.png",
        date:"03 MAR",
        category:"LIFESTYLE",
        author:"A.Tomson",
        title:"The Paint Colors You're Going to See Everywhere in 2021",
        text:"Design professionals and decor enthusiasts get a thrill from predicting the paint colors that will reign supreme in the year ahead. While some hues, like blush and white, made the 2020 list and aren't going anywhere anytime soon, there are a host of other standout paint colors that you can expect to see in 2021.",
    },
    {
        id:12,
        image:"images/deliciousdessert.png",
        date:"03 MAR",
        category:"FOOD",
        author:"A.Tomson",
        title:"Top 10 delicious dessert trends for 2021",
        text:"We take a look at the biggest trends in desserts, treats and puddings that will be satisfying your sweet tooth in the coming year.",
    },
]

export default blogPosts